version: '3'

services:
  openvpn-client:
    build:
      context: ./openvpn-client
    volumes:
      - ./openvpn-client:/etc/openvpn
    ports:
      - 1194
    networks:
      - vpn-net

  v2ray:
    build:
      context: ./v2ray
    volumes:
      - ./v2ray:/etc/v2ray
    ports:
      - 443:443
    depends_on:
      - openvpn-client
    networks:
      - vpn-net

networks:
  vpn-net:
    driver: bridge
