version: '3'

services:
  wireguard-client:
    build:
      context: ./wireguard
    ports:
      - 9050:1080
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    networks:
      - net
    restart: unless-stopped

  v2ray:
    build:
      context: ./v2ray
    volumes:
      - ./v2ray:/etc/v2ray
    ports:
      - 8443:8443
    networks:
      - net
    depends_on:
      - wireguard-client

  
  nginx:
    build:
      context: ./nginx
    volumes:
      - ./nginx:/etc/nginx
    ports:
      - 443:443
      - 80:80
    depends_on:
      - v2ray
    networks:
      - net
    restart: always

networks:
  net:
    driver: bridge